# it's-a-me!
name: "Stellenbauchery by Julia Burke"
description: "The South African wine blog and freelance writing site of Julia Burke."
domain: "stellenbauchery.com"

# included modules
markdown: redcarpet
pygments: false

# blog configuration
permalink: /blog/:month-:day-:year/:title.html
paginate: 5
paginate_path: 'blog/page:num'
